### ISSUE TITLE
build_model没有找到

### ISSUE THREAD

**Issue by zz978233034** [libertyhhn/AR-DMVC#1]
作者您好，请问build_model这个脚本文件在哪里呀？我没有找到，可以提供一下吗？谢谢

**Comment by libertyhhn** [comment]
感谢您对我们的工作感兴趣，很抱歉由于我们的疏忽没有更新文件，我已经在 AR-DMVC/models 中上传了对应的文件

**Comment by zz978233034** [comment]
谢谢
